// design-tokens.d.ts — generated by dsys
// Do not edit manually — re-run dsys to regenerate

/**
 * Union type of all semantic color token names.
 * Use with CSS custom property access: `var(--ds-color-${token})`
 */
export type DSColorToken =
  | "action-primary" | "action-secondary" | "action-destructive"
  | "surface-default" | "surface-raised" | "surface-overlay" | "surface-inset"
  | "text-primary" | "text-secondary" | "text-muted" | "text-inverse" | "text-link"
  | "border-default" | "border-focus"
  | "feedback-success" | "feedback-error" | "feedback-warning" | "feedback-info";

/**
 * Union type of all spacing scale keys.
 * Matches the numeric keys in tokens.spacing.scale from design-system.json.
 * Use with CSS custom property: `var(--ds-spacing-${step})`
 */
export type DSSpacingStep = 1 | 2 | 3 | 4 | 5 | 6 | 8 | 10 | 12 | 16 | 20 | 24 | 32;

/**
 * Union type of border radius step names.
 * Use with CSS custom property: `var(--ds-radius-${step})`
 */
export type DSRadiusStep = "sm" | "md" | "lg" | "full";

/**
 * Union type of type scale step names.
 * Matches the keys in tokens.typography.scale from design-system.json.
 * Use with CSS custom property: `var(--ds-font-size-${step})`
 */
export type DSFontSize = "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl" | "4xl" | "5xl";
