// Colors+DesignSystem.swift
// Generated by dsys — do not edit manually

import SwiftUI

public extension Color {
    // ── Action tokens ──
    static let dsActionPrimary     = Color("dsActionPrimary",     bundle: .module)
    static let dsActionSecondary   = Color("dsActionSecondary",   bundle: .module)
    static let dsActionDestructive = Color("dsActionDestructive", bundle: .module)

    // ── Surface tokens ──
    static let dsSurfaceDefault    = Color("dsSurfaceDefault",    bundle: .module)
    static let dsSurfaceRaised     = Color("dsSurfaceRaised",     bundle: .module)
    static let dsSurfaceOverlay    = Color("dsSurfaceOverlay",    bundle: .module)
    static let dsSurfaceInset      = Color("dsSurfaceInset",      bundle: .module)

    // ── Text tokens ──
    static let dsTextPrimary       = Color("dsTextPrimary",       bundle: .module)
    static let dsTextSecondary     = Color("dsTextSecondary",     bundle: .module)
    static let dsTextMuted         = Color("dsTextMuted",         bundle: .module)
    static let dsTextInverse       = Color("dsTextInverse",       bundle: .module)
    static let dsTextLink          = Color("dsTextLink",          bundle: .module)

    // ── Border tokens ──
    static let dsBorderDefault     = Color("dsBorderDefault",     bundle: .module)
    static let dsBorderFocus       = Color("dsBorderFocus",       bundle: .module)

    // ── Feedback tokens ──
    static let dsFeedbackSuccess   = Color("dsFeedbackSuccess",   bundle: .module)
    static let dsFeedbackError     = Color("dsFeedbackError",     bundle: .module)
    static let dsFeedbackWarning   = Color("dsFeedbackWarning",   bundle: .module)
    static let dsFeedbackInfo      = Color("dsFeedbackInfo",      bundle: .module)
}
