// DesignSystem.swift
// Generated by dsys — do not edit manually
// Re-imports all design system tokens and components for single-import convenience

// Token extensions (Colors+DesignSystem, Typography+DesignSystem, Spacing+DesignSystem,
// Radius+DesignSystem, Shadows+DesignSystem) and components (DSButton, DSCard, DSInput,
// DSBadge, DSHeading, DSText) are all part of the same module.
// After adding this package to your project, a single `import DesignSystem` exposes all types.

import SwiftUI

// Public type aliases for discoverability in autocomplete
public typealias DesignSystemFont    = DSFont
// Usage: DSFont.body(), DSFont.heading1(), DSFont.code()

public typealias DesignSystemRadius  = DSRadius
// Usage: DSRadius.sm, DSRadius.md, DSRadius.lg, DSRadius.full

public typealias DesignSystemShadow  = DSShadowSize
// Usage: .dsShadow(.sm), .dsShadow(.md), .dsShadow(.lg)

// Color tokens are accessed via Color extensions:
// Color.dsActionPrimary, Color.dsSurfaceDefault, Color.dsTextPrimary, etc.

// Spacing tokens:
// var spacing = DSSpacing()  — instance with @ScaledMetric Dynamic Type scaling
// DSSpacingFixed.md          — static CGFloat for layout constraints
