// Radius+DesignSystem.swift
// Generated by dsys — do not edit manually
// Source: Luxora design-system.json — border_radius: sm=8px, md=16px, lg=24px, full=9999px

import SwiftUI

public enum DSRadius {
    public static let none: CGFloat = 0
    public static let sm:   CGFloat = 8     // border_radius.sm
    public static let md:   CGFloat = 16    // border_radius.md
    public static let lg:   CGFloat = 24    // border_radius.lg
    public static let full: CGFloat = 9999  // border_radius.full
}
