// Shadows+DesignSystem.swift
// Generated by dsys — do not edit manually
// Source: Luxora design-system.json — shadow[0]: elevation=sm, offsetY=2px, blur=8px, color=#0000000F
// #0000000F: alpha = 0x0F = 15, 15/255 ≈ 0.059

import SwiftUI

public enum DSShadowSize { case sm, md, lg }

struct DSShadowModifier: ViewModifier {
    let size: DSShadowSize

    func body(content: Content) -> some View {
        switch size {
        case .sm:
            // From design-system.json shadow[elevation="sm"]
            content.shadow(color: .black.opacity(0.059), radius: 8, x: 0, y: 2)
        case .md:
            // Default (not in design-system.json)
            content.shadow(color: .black.opacity(0.10), radius: 6, x: 0, y: 4)
        case .lg:
            // Default (not in design-system.json)
            content.shadow(color: .black.opacity(0.10), radius: 15, x: 0, y: 10)
        }
    }
}

public extension View {
    func dsShadow(_ size: DSShadowSize = .md) -> some View {
        modifier(DSShadowModifier(size: size))
    }
}
