// Spacing+DesignSystem.swift
// Generated by dsys — do not edit manually
// Source: Luxora design-system.json — spacing.base_unit = 4

import SwiftUI

// Dynamic Type-aware spacing: use DSSpacing() as an instance in views
// that should scale with the user's preferred text size.
public struct DSSpacing {
    @ScaledMetric(relativeTo: .body) public var xs:  CGFloat = 4
    @ScaledMetric(relativeTo: .body) public var sm:  CGFloat = 8
    @ScaledMetric(relativeTo: .body) public var md:  CGFloat = 16
    @ScaledMetric(relativeTo: .body) public var lg:  CGFloat = 24
    @ScaledMetric(relativeTo: .body) public var xl:  CGFloat = 32
    @ScaledMetric(relativeTo: .body) public var xxl: CGFloat = 48

    public init() {}
}

// Fixed (non-scaling) spacing values for layout constraints that must not grow with text size.
public enum DSSpacingFixed {
    public static let xs:  CGFloat = 4
    public static let sm:  CGFloat = 8
    public static let md:  CGFloat = 16
    public static let lg:  CGFloat = 24
    public static let xl:  CGFloat = 32
    public static let xxl: CGFloat = 48
}
