// Typography+DesignSystem.swift
// Generated by dsys — do not edit manually
// Source: Luxora design-system.json — font_family.sans = "Satoshi", mono = null, display = null

import SwiftUI

public struct DSFont {
    private init() {}

    // ── Display / Heading ──
    // font_family.display is null — falling through to sans (Satoshi)
    public static func display() -> Font {
        .custom("Satoshi", size: 48, relativeTo: .largeTitle)
    }

    public static func heading1() -> Font {
        .custom("Satoshi", size: 40, relativeTo: .largeTitle)
    }

    public static func heading2() -> Font {
        .custom("Satoshi", size: 32, relativeTo: .title)
    }

    public static func heading3() -> Font {
        .custom("Satoshi", size: 24, relativeTo: .title2)
    }

    public static func heading4() -> Font {
        .custom("Satoshi", size: 20, relativeTo: .title3)
    }

    // ── Body ──
    public static func bodyLarge() -> Font {
        .custom("Satoshi", size: 16, relativeTo: .body)
    }

    public static func body() -> Font {
        .custom("Satoshi", size: 14, relativeTo: .body)
    }

    public static func bodySmall() -> Font {
        .custom("Satoshi", size: 13, relativeTo: .callout)
    }

    // ── Supporting ──
    public static func caption() -> Font {
        .custom("Satoshi", size: 12, relativeTo: .caption)
    }

    public static func label() -> Font {
        .custom("Satoshi", size: 12, relativeTo: .caption2)
    }

    // ── Monospace ──
    // font_family.mono is null — using system monospaced fallback
    public static func code() -> Font {
        .system(size: 14, design: .monospaced)
    }
}
