// Badge.tsx — generated by dsys
// Do not edit manually — re-run dsys to regenerate

import { forwardRef } from "react";

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: "default" | "success" | "error" | "warning" | "info";
}

const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  ({ variant = "default", className, children, ...props }, ref) => {
    const variants = {
      default: "bg-surface-inset text-text-muted border-border",
      success: "bg-success/10 text-success border-success/20",
      error:   "bg-error/10 text-error border-error/20",
      warning: "bg-warning/10 text-warning border-warning/20",
      info:    "bg-info/10 text-info border-info/20",
    };
    return (
      <span
        ref={ref}
        className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium ${variants[variant]} ${className ?? ""}`}
        {...props}
      >
        {children}
      </span>
    );
  }
);
Badge.displayName = "Badge";
export default Badge;
