// Button.tsx — generated by dsys
// Do not edit manually — re-run dsys to regenerate

import { forwardRef } from "react";

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary" | "destructive" | "ghost" | "outline";
  size?: "sm" | "md" | "lg";
  isLoading?: boolean;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ variant = "primary", size = "md", isLoading = false, className, children, ...props }, ref) => {
    const variants = {
      primary:     "bg-primary text-inverse hover:bg-primary/90 focus-visible:outline-focus",
      secondary:   "bg-surface-raised text-text border border-border hover:bg-surface-inset focus-visible:outline-focus",
      destructive: "bg-destructive text-inverse hover:bg-destructive/90 focus-visible:outline-focus",
      ghost:       "bg-transparent text-text hover:bg-surface-inset focus-visible:outline-focus",
      outline:     "bg-transparent text-text border border-border hover:bg-surface-inset focus-visible:outline-focus",
    };
    const sizes = {
      sm: "px-3 py-1.5 text-sm rounded-sm",
      md: "px-4 py-2 text-base rounded-md",
      lg: "px-6 py-3 text-lg rounded-lg",
    };
    return (
      <button
        ref={ref}
        disabled={isLoading || props.disabled}
        className={`inline-flex items-center justify-center gap-2 font-medium transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 disabled:pointer-events-none disabled:opacity-50 ${variants[variant]} ${sizes[size]} ${className ?? ""}`}
        aria-busy={isLoading}
        {...props}
      >
        {isLoading && (
          <span
            className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent"
            aria-hidden="true"
          />
        )}
        {children}
      </button>
    );
  }
);
Button.displayName = "Button";
export default Button;
