// Card.tsx — generated by dsys
// Do not edit manually — re-run dsys to regenerate

import { forwardRef } from "react";

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {}

const Card = forwardRef<HTMLDivElement, CardProps>(
  ({ className, children, ...props }, ref) => (
    <div
      ref={ref}
      className={`bg-surface-raised rounded-lg border border-border shadow-sm ${className ?? ""}`}
      {...props}
    >
      {children}
    </div>
  )
);
Card.displayName = "Card";
export default Card;
