// Input.tsx — generated by dsys
// Do not edit manually — re-run dsys to regenerate

import { forwardRef } from "react";

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  size?: "sm" | "md" | "lg";
  error?: boolean;
}

const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ size = "md", error = false, className, ...props }, ref) => {
    const sizes = {
      sm: "px-2.5 py-1.5 text-sm",
      md: "px-3 py-2 text-base",
      lg: "px-4 py-3 text-lg",
    };
    return (
      <input
        ref={ref}
        className={`w-full rounded-md border bg-surface-inset text-text placeholder:text-text-muted transition-colors focus:outline-none focus:ring-2 focus:ring-focus focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${
          error ? "border-error" : "border-border"
        } ${sizes[size]} ${className ?? ""}`}
        {...props}
      />
    );
  }
);
Input.displayName = "Input";
export default Input;
