// Text.tsx — generated by dsys
// Do not edit manually — re-run dsys to regenerate

import { forwardRef } from "react";

export interface TextProps extends React.HTMLAttributes<HTMLParagraphElement> {
  variant?: "primary" | "secondary" | "muted";
  size?: "sm" | "base" | "lg";
  as?: "p" | "span" | "div";
}

const Text = forwardRef<HTMLParagraphElement, TextProps>(
  ({ variant = "primary", size = "base", as: Tag = "p", className, children, ...props }, ref) => {
    const variants = {
      primary:   "text-text",
      secondary: "text-text-secondary",
      muted:     "text-text-muted",
    };
    const sizes = {
      sm:   "text-sm",
      base: "text-base",
      lg:   "text-lg",
    };
    return (
      <Tag
        ref={ref as React.Ref<HTMLParagraphElement>}
        className={`leading-relaxed ${variants[variant]} ${sizes[size]} ${className ?? ""}`}
        {...props}
      >
        {children}
      </Tag>
    );
  }
);
Text.displayName = "Text";
export default Text;
