// DSBadge.swift
// Generated by dsys — do not edit manually

import SwiftUI

public struct DSBadge: View {
    public enum Variant { case `default`, success, error, warning, info }

    let label: String
    let variant: Variant

    public init(_ label: String, variant: Variant = .default) {
        self.label = label
        self.variant = variant
    }

    public var body: some View {
        Text(label)
            .font(DSFont.label())
            .fontWeight(.medium)
            .foregroundStyle(foregroundColor)
            .padding(.horizontal, DSSpacingFixed.sm + DSSpacingFixed.xs)  // 12
            .padding(.vertical, DSSpacingFixed.xs / 2)                    // 2
            .background(backgroundColor)
            .clipShape(Capsule())
            .overlay(Capsule().stroke(borderColor, lineWidth: 1))
            .accessibilityLabel(label)
    }

    private var foregroundColor: Color {
        switch variant {
        case .default: return .dsTextMuted
        case .success: return .dsFeedbackSuccess
        case .error:   return .dsFeedbackError
        case .warning: return .dsFeedbackWarning
        case .info:    return .dsFeedbackInfo
        }
    }

    private var backgroundColor: Color {
        switch variant {
        case .default: return .dsSurfaceInset
        case .success: return .dsFeedbackSuccess.opacity(0.1)
        case .error:   return .dsFeedbackError.opacity(0.1)
        case .warning: return .dsFeedbackWarning.opacity(0.1)
        case .info:    return .dsFeedbackInfo.opacity(0.1)
        }
    }

    private var borderColor: Color {
        switch variant {
        case .default: return .dsBorderDefault
        case .success: return .dsFeedbackSuccess.opacity(0.2)
        case .error:   return .dsFeedbackError.opacity(0.2)
        case .warning: return .dsFeedbackWarning.opacity(0.2)
        case .info:    return .dsFeedbackInfo.opacity(0.2)
        }
    }
}

// #Preview requires Xcode 15 or later. Remove if using an older Xcode version.
#Preview {
    HStack(spacing: 8) {
        DSBadge("Default")
        DSBadge("Success", variant: .success)
        DSBadge("Error", variant: .error)
        DSBadge("Warning", variant: .warning)
        DSBadge("Info", variant: .info)
    }
    .padding()
    .background(Color.dsSurfaceDefault)
}
