// DSButton.swift
// Generated by dsys — do not edit manually

import SwiftUI

public struct DSButton: View {
    public enum Variant { case primary, secondary, destructive, ghost, outline }
    public enum Size { case sm, md, lg }

    let title: String
    let variant: Variant
    let size: Size
    let isLoading: Bool
    let action: () -> Void

    public init(
        _ title: String,
        variant: Variant = .primary,
        size: Size = .md,
        isLoading: Bool = false,
        action: @escaping () -> Void
    ) {
        self.title = title
        self.variant = variant
        self.size = size
        self.isLoading = isLoading
        self.action = action
    }

    private var spacing = DSSpacing()

    public var body: some View {
        Button(action: isLoading ? {} : action) {
            HStack(spacing: DSSpacingFixed.xs) {
                if isLoading {
                    ProgressView()
                        .progressViewStyle(CircularProgressViewStyle())
                        .scaleEffect(0.75)
                        .frame(width: 16, height: 16)
                        .foregroundStyle(foregroundColor)
                } else {
                    Text(title)
                        .font(labelFont)
                        .fontWeight(.medium)
                }
            }
            .padding(.horizontal, horizontalPadding)
            .padding(.vertical, verticalPadding)
        }
        .foregroundStyle(foregroundColor)
        .background(backgroundColor)
        .clipShape(RoundedRectangle(cornerRadius: cornerRadius))
        .overlay(borderOverlay)
        .disabled(isLoading)
        .accessibilityLabel(title)
        .accessibilityAddTraits(.isButton)
    }

    @ViewBuilder
    private var borderOverlay: some View {
        switch variant {
        case .outline:
            RoundedRectangle(cornerRadius: cornerRadius)
                .stroke(Color.dsBorderDefault, lineWidth: 1)
        default:
            EmptyView()
        }
    }

    private var foregroundColor: Color {
        switch variant {
        case .primary:     return .dsTextInverse
        case .secondary:   return .dsTextPrimary
        case .destructive: return .dsTextInverse
        case .ghost:       return .dsTextPrimary
        case .outline:     return .dsTextPrimary
        }
    }

    private var backgroundColor: Color {
        switch variant {
        case .primary:     return .dsActionPrimary
        case .secondary:   return .dsSurfaceRaised
        case .destructive: return .dsActionDestructive
        case .ghost:       return .clear
        case .outline:     return .clear
        }
    }

    private var labelFont: Font {
        switch size {
        case .sm: return DSFont.bodySmall()
        case .md: return DSFont.body()
        case .lg: return DSFont.bodyLarge()
        }
    }

    private var horizontalPadding: CGFloat {
        switch size {
        case .sm: return DSSpacingFixed.sm + DSSpacingFixed.xs   // 12
        case .md: return DSSpacingFixed.md                        // 16
        case .lg: return DSSpacingFixed.lg                        // 24
        }
    }

    private var verticalPadding: CGFloat {
        switch size {
        case .sm: return DSSpacingFixed.xs + 2                    // 6
        case .md: return DSSpacingFixed.sm                        // 8
        case .lg: return DSSpacingFixed.sm + DSSpacingFixed.xs    // 12
        }
    }

    private var cornerRadius: CGFloat {
        switch size {
        case .sm: return DSRadius.sm
        case .md: return DSRadius.md
        case .lg: return DSRadius.md
        }
    }
}

// #Preview requires Xcode 15 or later. Remove if using an older Xcode version.
#Preview {
    VStack(spacing: 16) {
        HStack(spacing: 8) {
            DSButton("Primary") {}
            DSButton("Secondary", variant: .secondary) {}
            DSButton("Danger", variant: .destructive) {}
        }
        HStack(spacing: 8) {
            DSButton("Ghost", variant: .ghost) {}
            DSButton("Outline", variant: .outline) {}
            DSButton("Loading", isLoading: true) {}
        }
        HStack(spacing: 8) {
            DSButton("Small", size: .sm) {}
            DSButton("Medium") {}
            DSButton("Large", size: .lg) {}
        }
    }
    .padding()
    .background(Color.dsSurfaceDefault)
}
