// DSCard.swift
// Generated by dsys — do not edit manually

import SwiftUI

public struct DSCard<Content: View>: View {
    let content: Content

    public init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }

    private var spacing = DSSpacing()

    public var body: some View {
        content
            .padding(spacing.md)
            .background(Color.dsSurfaceRaised)
            .clipShape(RoundedRectangle(cornerRadius: DSRadius.lg))
            .overlay(
                RoundedRectangle(cornerRadius: DSRadius.lg)
                    .stroke(Color.dsBorderDefault, lineWidth: 1)
            )
            .dsShadow(.sm)
    }
}

// #Preview requires Xcode 15 or later. Remove if using an older Xcode version.
#Preview {
    DSCard {
        VStack(alignment: .leading, spacing: 8) {
            Text("Card title")
                .font(DSFont.heading4())
                .foregroundStyle(Color.dsTextPrimary)
            Text("Supporting card content goes here.")
                .font(DSFont.body())
                .foregroundStyle(Color.dsTextMuted)
        }
    }
    .padding()
    .background(Color.dsSurfaceDefault)
}
