// DSHeading.swift
// Generated by dsys — do not edit manually

import SwiftUI

public struct DSHeading: View {
    public enum Level { case h1, h2, h3, h4 }

    let text: String
    let level: Level

    public init(_ text: String, level: Level = .h1) {
        self.text = text
        self.level = level
    }

    public var body: some View {
        Text(text)
            .font(headingFont)
            .fontWeight(fontWeight)
            .foregroundStyle(Color.dsTextPrimary)
            .lineSpacing(2)
            .accessibilityAddTraits(.isHeader)
    }

    private var headingFont: Font {
        switch level {
        case .h1: return DSFont.heading1()
        case .h2: return DSFont.heading2()
        case .h3: return DSFont.heading3()
        case .h4: return DSFont.heading4()
        }
    }

    private var fontWeight: Font.Weight {
        switch level {
        case .h1, .h2: return .bold
        case .h3, .h4: return .semibold
        }
    }
}

// #Preview requires Xcode 15 or later. Remove if using an older Xcode version.
#Preview {
    VStack(alignment: .leading, spacing: 16) {
        DSHeading("Heading 1")
        DSHeading("Heading 2", level: .h2)
        DSHeading("Heading 3", level: .h3)
        DSHeading("Heading 4", level: .h4)
    }
    .padding()
    .background(Color.dsSurfaceDefault)
}
