// DSInput.swift
// Generated by dsys — do not edit manually

import SwiftUI

public struct DSInput: View {
    public enum Size { case sm, md, lg }

    let placeholder: String
    @Binding var text: String
    var isError: Bool
    var size: Size

    @FocusState private var isFocused: Bool
    private var spacing = DSSpacing()

    public init(
        _ placeholder: String,
        text: Binding<String>,
        isError: Bool = false,
        size: Size = .md
    ) {
        self.placeholder = placeholder
        self._text = text
        self.isError = isError
        self.size = size
    }

    public var body: some View {
        TextField(placeholder, text: $text)
            .font(inputFont)
            .foregroundStyle(Color.dsTextPrimary)
            .padding(.horizontal, horizontalPadding)
            .padding(.vertical, verticalPadding)
            .background(Color.dsSurfaceInset)
            .clipShape(RoundedRectangle(cornerRadius: DSRadius.md))
            .overlay(
                RoundedRectangle(cornerRadius: DSRadius.md)
                    .stroke(borderColor, lineWidth: isFocused ? 2 : 1)
            )
            .focused($isFocused)
            .accessibilityLabel(placeholder)
    }

    private var borderColor: Color {
        if isError   { return .dsFeedbackError }
        if isFocused { return .dsBorderFocus }
        return .dsBorderDefault
    }

    private var inputFont: Font {
        switch size {
        case .sm: return DSFont.bodySmall()
        case .md: return DSFont.body()
        case .lg: return DSFont.bodyLarge()
        }
    }

    private var horizontalPadding: CGFloat {
        switch size {
        case .sm: return DSSpacingFixed.sm         // 8
        case .md: return DSSpacingFixed.md         // 16
        case .lg: return DSSpacingFixed.md         // 16
        }
    }

    private var verticalPadding: CGFloat {
        switch size {
        case .sm: return DSSpacingFixed.xs         // 4
        case .md: return DSSpacingFixed.sm         // 8
        case .lg: return DSSpacingFixed.sm + 4     // 12
        }
    }
}

// #Preview requires Xcode 15 or later. Remove if using an older Xcode version.
#Preview {
    @State var text = ""
    @State var errorText = "invalid@"

    return VStack(spacing: 16) {
        DSInput("Email address (sm)", text: $text, size: .sm)
        DSInput("Email address (md)", text: $text)
        DSInput("Email address (lg)", text: $text, size: .lg)
        DSInput("Invalid input", text: $errorText, isError: true)
    }
    .padding()
    .background(Color.dsSurfaceDefault)
}
