// DSText.swift
// Generated by dsys — do not edit manually

import SwiftUI

public struct DSText: View {
    public enum Variant { case primary, secondary, muted }
    public enum Size { case sm, base, lg }

    let content: String
    let variant: Variant
    let size: Size

    public init(_ content: String, variant: Variant = .primary, size: Size = .base) {
        self.content = content
        self.variant = variant
        self.size = size
    }

    public var body: some View {
        Text(content)
            .font(textFont)
            .foregroundStyle(foregroundColor)
            .lineSpacing(4)
    }

    private var textFont: Font {
        switch size {
        case .sm:   return DSFont.bodySmall()
        case .base: return DSFont.body()
        case .lg:   return DSFont.bodyLarge()
        }
    }

    private var foregroundColor: Color {
        switch variant {
        case .primary:   return .dsTextPrimary
        case .secondary: return .dsTextSecondary
        case .muted:     return .dsTextMuted
        }
    }
}

// #Preview requires Xcode 15 or later. Remove if using an older Xcode version.
#Preview {
    VStack(alignment: .leading, spacing: 12) {
        DSText("Primary text at base size")
        DSText("Secondary text at base size", variant: .secondary)
        DSText("Muted caption text", variant: .muted, size: .sm)
        DSText("Large body text", size: .lg)
    }
    .padding()
    .background(Color.dsSurfaceDefault)
}
